name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  report-only-changed-files:
    required: false
    default: false
  create-new-comment:
    required: false
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
